matrix:
  include:
  - env: Ubuntu=14.04
    os: linux
    dist: trusty
    sudo: required
before_install:
- "./.ci/before_install.sh"
install:
- "./.ci/install.sh"
script:
- "./.ci/script.sh"
git:
  depth: 3
notifications:
  slack:
    matrix:
    - everestexpedition:9XHKcyq8Ia6NcR6zLZvj2aNt
    rooms:
      secure: UW+6YQUzDFqMICIMC6XZ7t3GFzcBqvRYEQJLqH0SQ7DqUscog9Qxf53e1wsWKThePLdI6PlEgc+jd8dqb0RU+rFuwBET1qKHBDGYF9CqpAgL9hxCT9ht5SdmaD+kCItOyKE6YKNGkp21mEYwlxfmDb7rrt3+1lXv+nm4ePY9U4DPNfdrYOcaCE+3JHjUlJYJzJ2JY0zzKGWN6tq4vVlrUbn24/Fdo0iASBd4wvgj0CKznd6zZhG8qvaegjrhl29fvImSiKhrfBSGs2Mc7idse2jrvNBToTAlN2kEDGFjy8GjJ+SJxk218KBsRR5LgzQWyCXSUtFpEkTdPP9H8go/FTZIqHIm0aYdyngDNySqb11dyRFHaF+U18erbrfPX5FnAPyVMpHBov4lmCsFGh+LwUXWmlyry0Uwk1glH5rG6cSbQbEJW/EnZKpz3Jkgb6Ce5DDCPfPFKg/JxXpTvk/JRxR2TOxTJpUJCcqEFjI+tdORb5CHjH7bPsBYBRMAge/HmDgH1ncSt3IkxV9duzMV7Go5z5KnRORMTXD1Uv6ezuLwV7PoDxhPUMQWBD0dDMgWulXzw0VgOl2sqYZ1zQlUzsvIRNebLtzfTCBhir7tHVrfQ2JlQGQK1HfB+Wn43/kESggSB6Ek/tQDl4YO1+xX0tYWuSgWfkvnIVs1xutGuTk=
