name: Build and test Karamel
on: push
jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: Build Karamel and its dependencies
        run: |
          docker build -f .docker/standalone.Dockerfile .
